# here keys are names of the tasks
ComposerClassificationASAP:
    metadata_csv_path: data/datasets/composer_and_retrieval_datasets_new/metadata_composer_dataset.csv # path to CSV with target labels and filenames
    files_dir_path: data/datasets/composer_and_retrieval_datasets_new/ # path to directory with MIDI files from composer benchmark
ScorePerformanceRetrievalASAP:
    metadata_csv_path: data/datasets/composer_and_retrieval_datasets_new/metadata_retrieval_dataset.csv # path to CSV with scores and perfomances
    files_dir_path: data/datasets/composer_and_retrieval_datasets_new/ # path to directory with MIDI files from retrieval benchmark
GenreClassificationMMD:
    metadata_csv_path: data/datasets/genre_dataset/metadata_genre_dataset.csv
    files_dir_path: data/datasets/genre_dataset/midis/
GenreClassificationWMTX:
    metadata_csv_path: data/datasets/wikimtx_dataset/metadata_wikimtx_dataset.csv
    files_dir_path: data/datasets/wikimtx_dataset/midis/
EmotionClassificationEMOPIA:
    metadata_csv_path: data/datasets/emopia_dataset/metadata_emopia_dataset.csv
    files_dir_path: data/datasets/emopia_dataset/midis/
EmotionClassificationMIREX:
    metadata_csv_path: data/datasets/mirex_dataset/metadata_mirex_dataset.csv
    files_dir_path: data/datasets/mirex_dataset/midis/
InstrumentDetectionMMD:
    metadata_csv_path: data/datasets/instrument_dataset/metadata_instrument_dataset.csv
    files_dir_path: data/datasets/instrument_dataset/midis/